Traceback (most recent call last):
  File "/home/runner/.local/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/runner/.local/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/runner/.local/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/runner/.local/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/runner/.local/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/runner/.local/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/.local/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import spacy
import dacy

from dacy.datasets import dane

# load the DaNE test set
test = dane(splits=["test"])

# load models
spacy_small = spacy.load("da_core_news_sm")
dacy_small = dacy.load("small")
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mConnectionRefusedError[0m                    Traceback (most recent call last)
File [0;32m/usr/lib/python3.10/urllib/request.py:1348[0m, in [0;36mAbstractHTTPHandler.do_open[0;34m(self, http_class, req, **http_conn_args)[0m
[1;32m   1347[0m [38;5;28;01mtry[39;00m:
[0;32m-> 1348[0m     [43mh[49m[38;5;241;43m.[39;49m[43mrequest[49m[43m([49m[43mreq[49m[38;5;241;43m.[39;49m[43mget_method[49m[43m([49m[43m)[49m[43m,[49m[43m [49m[43mreq[49m[38;5;241;43m.[39;49m[43mselector[49m[43m,[49m[43m [49m[43mreq[49m[38;5;241;43m.[39;49m[43mdata[49m[43m,[49m[43m [49m[43mheaders[49m[43m,[49m
[1;32m   1349[0m [43m              [49m[43mencode_chunked[49m[38;5;241;43m=[39;49m[43mreq[49m[38;5;241;43m.[39;49m[43mhas_header[49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43mTransfer-encoding[39;49m[38;5;124;43m'[39;49m[43m)[49m[43m)[49m
[1;32m   1350[0m [38;5;28;01mexcept[39;00m [38;5;167;01mOSError[39;00m [38;5;28;01mas[39;00m err: [38;5;66;03m# timeout error[39;00m

File [0;32m/usr/lib/python3.10/http/client.py:1282[0m, in [0;36mHTTPConnection.request[0;34m(self, method, url, body, headers, encode_chunked)[0m
[1;32m   1281[0m [38;5;250m[39m[38;5;124;03m"""Send a complete request to the server."""[39;00m
[0;32m-> 1282[0m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_send_request[49m[43m([49m[43mmethod[49m[43m,[49m[43m [49m[43murl[49m[43m,[49m[43m [49m[43mbody[49m[43m,[49m[43m [49m[43mheaders[49m[43m,[49m[43m [49m[43mencode_chunked[49m[43m)[49m

File [0;32m/usr/lib/python3.10/http/client.py:1328[0m, in [0;36mHTTPConnection._send_request[0;34m(self, method, url, body, headers, encode_chunked)[0m
[1;32m   1327[0m     body [38;5;241m=[39m _encode(body, [38;5;124m'[39m[38;5;124mbody[39m[38;5;124m'[39m)
[0;32m-> 1328[0m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mendheaders[49m[43m([49m[43mbody[49m[43m,[49m[43m [49m[43mencode_chunked[49m[38;5;241;43m=[39;49m[43mencode_chunked[49m[43m)[49m

File [0;32m/usr/lib/python3.10/http/client.py:1277[0m, in [0;36mHTTPConnection.endheaders[0;34m(self, message_body, encode_chunked)[0m
[1;32m   1276[0m     [38;5;28;01mraise[39;00m CannotSendHeader()
[0;32m-> 1277[0m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_send_output[49m[43m([49m[43mmessage_body[49m[43m,[49m[43m [49m[43mencode_chunked[49m[38;5;241;43m=[39;49m[43mencode_chunked[49m[43m)[49m

File [0;32m/usr/lib/python3.10/http/client.py:1037[0m, in [0;36mHTTPConnection._send_output[0;34m(self, message_body, encode_chunked)[0m
[1;32m   1036[0m [38;5;28;01mdel[39;00m [38;5;28mself[39m[38;5;241m.[39m_buffer[:]
[0;32m-> 1037[0m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43msend[49m[43m([49m[43mmsg[49m[43m)[49m
[1;32m   1039[0m [38;5;28;01mif[39;00m message_body [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:
[1;32m   1040[0m 
[1;32m   1041[0m     [38;5;66;03m# create a consistent interface to message_body[39;00m

File [0;32m/usr/lib/python3.10/http/client.py:975[0m, in [0;36mHTTPConnection.send[0;34m(self, data)[0m
[1;32m    974[0m [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39mauto_open:
[0;32m--> 975[0m     [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mconnect[49m[43m([49m[43m)[49m
[1;32m    976[0m [38;5;28;01melse[39;00m:

File [0;32m/usr/lib/python3.10/http/client.py:1447[0m, in [0;36mHTTPSConnection.connect[0;34m(self)[0m
[1;32m   1445[0m [38;5;124m"[39m[38;5;124mConnect to a host on a given (SSL) port.[39m[38;5;124m"[39m
[0;32m-> 1447[0m [38;5;28;43msuper[39;49m[43m([49m[43m)[49m[38;5;241;43m.[39;49m[43mconnect[49m[43m([49m[43m)[49m
[1;32m   1449[0m [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39m_tunnel_host:

File [0;32m/usr/lib/python3.10/http/client.py:941[0m, in [0;36mHTTPConnection.connect[0;34m(self)[0m
[1;32m    940[0m sys[38;5;241m.[39maudit([38;5;124m"[39m[38;5;124mhttp.client.connect[39m[38;5;124m"[39m, [38;5;28mself[39m, [38;5;28mself[39m[38;5;241m.[39mhost, [38;5;28mself[39m[38;5;241m.[39mport)
[0;32m--> 941[0m [38;5;28mself[39m[38;5;241m.[39msock [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_create_connection[49m[43m([49m
[1;32m    942[0m [43m    [49m[43m([49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mhost[49m[43m,[49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mport[49m[43m)[49m[43m,[49m[43m [49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mtimeout[49m[43m,[49m[43m [49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43msource_address[49m[43m)[49m
[1;32m    943[0m [38;5;66;03m# Might fail in OSs that don't implement TCP_NODELAY[39;00m

File [0;32m/usr/lib/python3.10/socket.py:845[0m, in [0;36mcreate_connection[0;34m(address, timeout, source_address)[0m
[1;32m    844[0m [38;5;28;01mtry[39;00m:
[0;32m--> 845[0m     [38;5;28;01mraise[39;00m err
[1;32m    846[0m [38;5;28;01mfinally[39;00m:
[1;32m    847[0m     [38;5;66;03m# Break explicitly a reference cycle[39;00m

File [0;32m/usr/lib/python3.10/socket.py:833[0m, in [0;36mcreate_connection[0;34m(address, timeout, source_address)[0m
[1;32m    832[0m     sock[38;5;241m.[39mbind(source_address)
[0;32m--> 833[0m [43msock[49m[38;5;241;43m.[39;49m[43mconnect[49m[43m([49m[43msa[49m[43m)[49m
[1;32m    834[0m [38;5;66;03m# Break explicitly a reference cycle[39;00m

[0;31mConnectionRefusedError[0m: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

[0;31mURLError[0m                                  Traceback (most recent call last)
Cell [0;32mIn[1], line 7[0m
[1;32m      4[0m [38;5;28;01mfrom[39;00m [38;5;21;01mdacy[39;00m[38;5;21;01m.[39;00m[38;5;21;01mdatasets[39;00m [38;5;28;01mimport[39;00m dane
[1;32m      6[0m [38;5;66;03m# load the DaNE test set[39;00m
[0;32m----> 7[0m test [38;5;241m=[39m [43mdane[49m[43m([49m[43msplits[49m[38;5;241;43m=[39;49m[43m[[49m[38;5;124;43m"[39;49m[38;5;124;43mtest[39;49m[38;5;124;43m"[39;49m[43m][49m[43m)[49m
[1;32m      9[0m [38;5;66;03m# load models[39;00m
[1;32m     10[0m spacy_small [38;5;241m=[39m spacy[38;5;241m.[39mload([38;5;124m"[39m[38;5;124mda_core_news_sm[39m[38;5;124m"[39m)

File [0;32m~/.local/lib/python3.10/site-packages/dacy/datasets/dane.py:63[0m, in [0;36mdane[0;34m(save_path, splits, redownload, n_sents, open_unverified_connection, **kwargs)[0m
[1;32m     61[0m save_path[38;5;241m.[39mmkdir(parents[38;5;241m=[39m[38;5;28;01mTrue[39;00m, exist_ok[38;5;241m=[39m[38;5;28;01mTrue[39;00m)
[1;32m     62[0m dl_path [38;5;241m=[39m save_path [38;5;241m/[39m [38;5;124m"[39m[38;5;124mdane.zip[39m[38;5;124m"[39m
[0;32m---> 63[0m [43mdownload_url[49m[43m([49m[43mDATASETS[49m[43m[[49m[38;5;124;43m"[39;49m[38;5;124;43mdane[39;49m[38;5;124;43m"[39;49m[43m][49m[43m,[49m[43m [49m[38;5;28;43mstr[39;49m[43m([49m[43mdl_path[49m[43m)[49m[43m)[49m
[1;32m     64[0m shutil[38;5;241m.[39munpack_archive(dl_path, save_path)
[1;32m     65[0m dl_path[38;5;241m.[39munlink()

File [0;32m~/.local/lib/python3.10/site-packages/dacy/download.py:50[0m, in [0;36mdownload_url[0;34m(url, output_path)[0m
[1;32m     42[0m [38;5;28;01mimport[39;00m [38;5;21;01murllib[39;00m[38;5;21;01m.[39;00m[38;5;21;01mrequest[39;00m
[1;32m     44[0m [38;5;28;01mwith[39;00m DownloadProgressBar(
[1;32m     45[0m     unit[38;5;241m=[39m[38;5;124m"[39m[38;5;124mB[39m[38;5;124m"[39m,
[1;32m     46[0m     unit_scale[38;5;241m=[39m[38;5;28;01mTrue[39;00m,
[1;32m     47[0m     miniters[38;5;241m=[39m[38;5;241m1[39m,
[1;32m     48[0m     desc[38;5;241m=[39murl[38;5;241m.[39msplit([38;5;124m"[39m[38;5;124m/[39m[38;5;124m"[39m)[[38;5;241m-[39m[38;5;241m1[39m],
[1;32m     49[0m ) [38;5;28;01mas[39;00m t:
[0;32m---> 50[0m     [43murllib[49m[38;5;241;43m.[39;49m[43mrequest[49m[38;5;241;43m.[39;49m[43murlretrieve[49m[43m([49m[43murl[49m[43m,[49m[43m [49m[43mfilename[49m[38;5;241;43m=[39;49m[43moutput_path[49m[43m,[49m[43m [49m[43mreporthook[49m[38;5;241;43m=[39;49m[43mt[49m[38;5;241;43m.[39;49m[43mupdate_to[49m[43m)[49m

File [0;32m/usr/lib/python3.10/urllib/request.py:241[0m, in [0;36murlretrieve[0;34m(url, filename, reporthook, data)[0m
[1;32m    224[0m [38;5;250m[39m[38;5;124;03m"""[39;00m
[1;32m    225[0m [38;5;124;03mRetrieve a URL into a temporary location on disk.[39;00m
[1;32m    226[0m 
[0;32m   (...)[0m
[1;32m    237[0m [38;5;124;03mdata file as well as the resulting HTTPMessage object.[39;00m
[1;32m    238[0m [38;5;124;03m"""[39;00m
[1;32m    239[0m url_type, path [38;5;241m=[39m _splittype(url)
[0;32m--> 241[0m [38;5;28;01mwith[39;00m contextlib[38;5;241m.[39mclosing([43murlopen[49m[43m([49m[43murl[49m[43m,[49m[43m [49m[43mdata[49m[43m)[49m) [38;5;28;01mas[39;00m fp:
[1;32m    242[0m     headers [38;5;241m=[39m fp[38;5;241m.[39minfo()
[1;32m    244[0m     [38;5;66;03m# Just return the local path and the "headers" for file://[39;00m
[1;32m    245[0m     [38;5;66;03m# URLs. No sense in performing a copy unless requested.[39;00m

File [0;32m/usr/lib/python3.10/urllib/request.py:216[0m, in [0;36murlopen[0;34m(url, data, timeout, cafile, capath, cadefault, context)[0m
[1;32m    214[0m [38;5;28;01melse[39;00m:
[1;32m    215[0m     opener [38;5;241m=[39m _opener
[0;32m--> 216[0m [38;5;28;01mreturn[39;00m [43mopener[49m[38;5;241;43m.[39;49m[43mopen[49m[43m([49m[43murl[49m[43m,[49m[43m [49m[43mdata[49m[43m,[49m[43m [49m[43mtimeout[49m[43m)[49m

File [0;32m/usr/lib/python3.10/urllib/request.py:519[0m, in [0;36mOpenerDirector.open[0;34m(self, fullurl, data, timeout)[0m
[1;32m    516[0m     req [38;5;241m=[39m meth(req)
[1;32m    518[0m sys[38;5;241m.[39maudit([38;5;124m'[39m[38;5;124murllib.Request[39m[38;5;124m'[39m, req[38;5;241m.[39mfull_url, req[38;5;241m.[39mdata, req[38;5;241m.[39mheaders, req[38;5;241m.[39mget_method())
[0;32m--> 519[0m response [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_open[49m[43m([49m[43mreq[49m[43m,[49m[43m [49m[43mdata[49m[43m)[49m
[1;32m    521[0m [38;5;66;03m# post-process response[39;00m
[1;32m    522[0m meth_name [38;5;241m=[39m protocol[38;5;241m+[39m[38;5;124m"[39m[38;5;124m_response[39m[38;5;124m"[39m

File [0;32m/usr/lib/python3.10/urllib/request.py:536[0m, in [0;36mOpenerDirector._open[0;34m(self, req, data)[0m
[1;32m    533[0m     [38;5;28;01mreturn[39;00m result
[1;32m    535[0m protocol [38;5;241m=[39m req[38;5;241m.[39mtype
[0;32m--> 536[0m result [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_call_chain[49m[43m([49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mhandle_open[49m[43m,[49m[43m [49m[43mprotocol[49m[43m,[49m[43m [49m[43mprotocol[49m[43m [49m[38;5;241;43m+[39;49m
[1;32m    537[0m [43m                          [49m[38;5;124;43m'[39;49m[38;5;124;43m_open[39;49m[38;5;124;43m'[39;49m[43m,[49m[43m [49m[43mreq[49m[43m)[49m
[1;32m    538[0m [38;5;28;01mif[39;00m result:
[1;32m    539[0m     [38;5;28;01mreturn[39;00m result

File [0;32m/usr/lib/python3.10/urllib/request.py:496[0m, in [0;36mOpenerDirector._call_chain[0;34m(self, chain, kind, meth_name, *args)[0m
[1;32m    494[0m [38;5;28;01mfor[39;00m handler [38;5;129;01min[39;00m handlers:
[1;32m    495[0m     func [38;5;241m=[39m [38;5;28mgetattr[39m(handler, meth_name)
[0;32m--> 496[0m     result [38;5;241m=[39m [43mfunc[49m[43m([49m[38;5;241;43m*[39;49m[43margs[49m[43m)[49m
[1;32m    497[0m     [38;5;28;01mif[39;00m result [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:
[1;32m    498[0m         [38;5;28;01mreturn[39;00m result

File [0;32m/usr/lib/python3.10/urllib/request.py:1391[0m, in [0;36mHTTPSHandler.https_open[0;34m(self, req)[0m
[1;32m   1390[0m [38;5;28;01mdef[39;00m [38;5;21mhttps_open[39m([38;5;28mself[39m, req):
[0;32m-> 1391[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mdo_open[49m[43m([49m[43mhttp[49m[38;5;241;43m.[39;49m[43mclient[49m[38;5;241;43m.[39;49m[43mHTTPSConnection[49m[43m,[49m[43m [49m[43mreq[49m[43m,[49m
[1;32m   1392[0m [43m        [49m[43mcontext[49m[38;5;241;43m=[39;49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_context[49m[43m,[49m[43m [49m[43mcheck_hostname[49m[38;5;241;43m=[39;49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_check_hostname[49m[43m)[49m

File [0;32m/usr/lib/python3.10/urllib/request.py:1351[0m, in [0;36mAbstractHTTPHandler.do_open[0;34m(self, http_class, req, **http_conn_args)[0m
[1;32m   1348[0m         h[38;5;241m.[39mrequest(req[38;5;241m.[39mget_method(), req[38;5;241m.[39mselector, req[38;5;241m.[39mdata, headers,
[1;32m   1349[0m                   encode_chunked[38;5;241m=[39mreq[38;5;241m.[39mhas_header([38;5;124m'[39m[38;5;124mTransfer-encoding[39m[38;5;124m'[39m))
[1;32m   1350[0m     [38;5;28;01mexcept[39;00m [38;5;167;01mOSError[39;00m [38;5;28;01mas[39;00m err: [38;5;66;03m# timeout error[39;00m
[0;32m-> 1351[0m         [38;5;28;01mraise[39;00m URLError(err)
[1;32m   1352[0m     r [38;5;241m=[39m h[38;5;241m.[39mgetresponse()
[1;32m   1353[0m [38;5;28;01mexcept[39;00m:

[0;31mURLError[0m: <urlopen error [Errno 111] Connection refused>
URLError: <urlopen error [Errno 111] Connection refused>

